name: CI

on:
  push:
    branches:
      - master

jobs:
  buildTestDeploy:
    name: buildTestDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install deps
        run: yarn install
      - name: bundle
        run: yarn bundle
      - name: test
        run: yarn test
      # - name: terraform apply
      #   working-directory: infra/dev
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     TF_VAR_custom_api_domain_name: api.example.com
      #     TF_VAR_signing_secret: ${{ secrets.signing_secret }} # used to sign the function id
      #     TF_VAR_cloudflare_zone_id: ${{ secrets.cloudflare_zone_id }}
      #     TF_VAR_cloudflare_email: ${{ secrets.cloudflare_email }}
      #     TF_VAR_cloudflare_api_key: ${{ secrets.cloudflare_api_key }}
      #     TF_VAR_certificate_arn: ${{ secrets.certificate_arn }}
      #   run: |
      #     terraform init
      #     terraform apply -auto-approve
